
swagger: '2.0'
info:
  title: Hannibal
  description: Hannibaliapi-Sisäelinkaupalle
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /webstore: 
    get:
      summary: hakee tuotteen
      operationId: getproduct
      x-google-backend:
        address: https://us-central1-projekti4-testaus.cloudfunctions.net/hannibal-funktio #MUISTA VAIHTAA PROJEKTIN + FUNKTION NIMI
      responses:
        '200':
          description: 
          schema:
            type: string