
swagger: '2.0'
info:
  title: hannibal
  description: hannibaliapi-sisäelinkaupalle
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /webstore: 
    get:
      summary: hakee tuotteen
      operationId: getproduct
      x-google-backend:
        address: https://us-central1-testiproj.cloudfunctions.net/hannibal-funktio
      responses:
        '200':
          description: 
          schema:
            type: string